### model
model_name_or_path: /data/ckpt/wangning/codellama-13B/finetune/best

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
pref_loss: sigmoid  # [sigmoid (dpo), orpo, simpo]

### ddp
ddp_timeout: 180000000
deepspeed: rtllama/configs/deepspeed/ds_z3_config.json

### dataset
dataset: compiler_pairs
template: llama2
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/comp_pref
logging_steps: 1
# save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 0.000005
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500