### model
model_name_or_path: /data/ckpt/wangning/codellama-7B/pretrain/full_bf16_e1

### method
stage: sft
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: rtllama/configs/deepspeed/ds_z3_config.json

### dataset
dataset: instruct_data
template: llama2
cutoff_len: 4096
# max_samples: 13000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/finetune
logging_steps: 1
# save_steps: 13
save_only_model: True
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500

