### model
model_name_or_path: /data/ckpt/codellama/CodeLlama-70b-hf/

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

### ddp
ddp_timeout: 180000000
deepspeed: rtllama/configs/deepspeed/ds_z3_config.json

### dataset
dataset: vgen, gpu_sim
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: outputs/lora_bf16_1e
logging_steps: 1
# save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500

